services:
  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command:
      - redis-server
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379

  postgresdb:
    image: postgres:latest
    environment:
      POSTGRES_USER: dlc-db
      POSTGRES_PASSWORD: dlcdb-nopass
      POSTGRES_DB: watched-dlc
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  moviehandlerservice:
    image: moviehandlerservice
    build:
      context: .
      dockerfile: MovieHandlerService/Dockerfile
    depends_on:
      - postgresdb
    env_file:
      - ".env"

  twitchservice:
    image: twitchservice
    build:
      context: .
      dockerfile: TwitchService/Dockerfile
    depends_on:
      - postgresdb
      - moviehandlerservice
    env_file:
      - ".env"

  tests:
    image: tests
    build:
      context: .
      dockerfile: DatabaseService.Tests/Dockerfile
    depends_on:
      - redis
      - postgresdb

volumes:
  redis-data:
  postgres-data:

networks:
  default:
    driver: bridge